// <auto-generated />
using System;
using ISOAuditAgent.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISOAuditAgent.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ISOAuditAgentDbContext))]
    [Migration("20260517200128_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.ArtefactoEsperado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("descripcion");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int")
                        .HasColumnName("etapa_id");

                    b.Property<bool>("MandatorioTipoA")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("mandatorio_tipo_a");

                    b.Property<bool>("MandatorioTipoB")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("mandatorio_tipo_b");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TemplateDriveFilename")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("template_drive_filename");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId", "Codigo");

                    b.ToTable("artefacto_esperado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "FR 29",
                            Descripcion = "Excel que define qué del procedimiento aplica a este proyecto. Piedra fundacional de la auditoría.",
                            EtapaId = 1,
                            MandatorioTipoA = true,
                            MandatorioTipoB = true,
                            Nombre = "Tailoring del Proyecto",
                            TemplateDriveFilename = "FR-29.xlsx"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "FR 30",
                            Descripcion = "Documento que captura los requerimientos funcionales y no funcionales del proyecto.",
                            EtapaId = 2,
                            MandatorioTipoA = true,
                            MandatorioTipoB = false,
                            Nombre = "Especificación de Requerimiento de Software (ERS)",
                            TemplateDriveFilename = "FR-30.docx"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "FR 32",
                            Descripcion = "Matriz de casos de prueba funcionales sobre el producto.",
                            EtapaId = 4,
                            MandatorioTipoA = true,
                            MandatorioTipoB = false,
                            Nombre = "Casos de Prueba",
                            TemplateDriveFilename = "FR-32.xlsx"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "FR 48",
                            Descripcion = "Conformidad escrita del cliente sobre la entrega del producto.",
                            EtapaId = 5,
                            MandatorioTipoA = true,
                            MandatorioTipoB = true,
                            Nombre = "Sign-Off",
                            TemplateDriveFilename = "FR-48.docx"
                        });
                });

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.ConfiguracionSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("configuracion_sistema", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clave = "drive_carpeta_templates_id",
                            Descripcion = "FolderId de Drive donde viven los templates de los FRs. Se compone con ArtefactoEsperado.TemplateDriveFilename para resolver cada template específico. Reemplazar por el FolderId real cuando exista la carpeta en el Drive de BDT.",
                            Valor = "REEMPLAZAR_POR_FOLDERID_REAL"
                        });
                });

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<int>("ProcedimientoId")
                        .HasColumnType("int")
                        .HasColumnName("procedimiento_id");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoId", "Orden")
                        .IsUnique();

                    b.ToTable("etapa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Definición inicial del proyecto, alcance y tailoring.",
                            Nombre = "Planificación",
                            Orden = 1,
                            ProcedimientoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Relevamiento, ERS y diseño técnico.",
                            Nombre = "Análisis y Diseño",
                            Orden = 2,
                            ProcedimientoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Construcción del producto de software.",
                            Nombre = "Desarrollo",
                            Orden = 3,
                            ProcedimientoId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Pruebas funcionales y casos de prueba.",
                            Nombre = "Testing",
                            Orden = 4,
                            ProcedimientoId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Despliegue, sign-off y entrega al cliente.",
                            Nombre = "Implementación",
                            Orden = 5,
                            ProcedimientoId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Seguimiento post-implementación y control de costos.",
                            Nombre = "Seguimiento",
                            Orden = 6,
                            ProcedimientoId = 1
                        });
                });

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.Procedimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("procedimiento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PR 11-13",
                            Descripcion = "Procedimiento maestro de BDT para proyectos de desarrollo de software (llave en mano y customizaciones). Define las etapas del ciclo de vida y los artefactos esperados en cada una.",
                            Nombre = "Diseño y Análisis, Desarrollo e Implementación de Software"
                        });
                });

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("ClockifyProjectId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clockify_project_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DriveFolderId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("drive_folder_id");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<decimal>("HorasEstimadas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("horas_estimadas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("ProcedimientoId")
                        .HasColumnType("int")
                        .HasColumnName("procedimiento_id");

                    b.Property<string>("TipoProyecto")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("tipo_proyecto");

                    b.Property<string>("TrelloBoardId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("trello_board_id");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoId");

                    b.ToTable("proyecto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Proyecto de prueba usado para validación end-to-end del agente. Reemplaza el mapeo que vivía en appsettings.json:DocumentAnalysis:Drive:Mappings.",
                            DriveFolderId = "15Y7zY72QGzVlN2CqDDRFaUwVZNngLT5n",
                            FechaInicio = new DateOnly(2026, 1, 1),
                            HorasEstimadas = 1500m,
                            Nombre = "Proyecto de prueba (30.052)",
                            ProcedimientoId = 1,
                            TipoProyecto = "A"
                        });
                });

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.ArtefactoEsperado", b =>
                {
                    b.HasOne("ISOAuditAgent.Infrastructure.Entities.Etapa", "Etapa")
                        .WithMany("ArtefactosEsperados")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.Etapa", b =>
                {
                    b.HasOne("ISOAuditAgent.Infrastructure.Entities.Procedimiento", "Procedimiento")
                        .WithMany("Etapas")
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.Proyecto", b =>
                {
                    b.HasOne("ISOAuditAgent.Infrastructure.Entities.Procedimiento", "Procedimiento")
                        .WithMany()
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.Etapa", b =>
                {
                    b.Navigation("ArtefactosEsperados");
                });

            modelBuilder.Entity("ISOAuditAgent.Infrastructure.Entities.Procedimiento", b =>
                {
                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
