// <auto-generated />
using System;
using ISOAuditAgent.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISOAuditAgent.API.Migrations
{
    [DbContext(typeof(ISOAuditAgentDbContext))]
    [Migration("20260701005131_AgregarPromptAgente")]
    partial class AgregarPromptAgente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEsperado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<string>("FuenteVerificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("MandatorioTipoA")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MandatorioTipoB")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PathTemplateRelativo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.ToTable("artefactos_esperados", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEvaluado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aplica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ArtefactoEsperadoId")
                        .HasColumnType("int");

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int");

                    b.Property<string>("JustificacionNoAplica")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ArtefactoEsperadoId");

                    b.HasIndex("AuditoriaId");

                    b.ToTable("artefactos_evaluados", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFinalizacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditorias", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.AuditoriaProgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaFinUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicioUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nodo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AuditoriaId", "Nodo")
                        .IsUnique();

                    b.ToTable("auditoria_progreso", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ConfiguracionSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("configuraciones_sistema", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.DocumentoAnalizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtefactoEvaluadoId")
                        .HasColumnType("int");

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashContenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlReferencia")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ArtefactoEvaluadoId");

                    b.HasIndex("AuditoriaId");

                    b.ToTable("documentos_analizados", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("ProcedimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoId");

                    b.ToTable("etapas", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.FormularioCalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoFormulario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("VigenciaVigente")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CodigoFormulario")
                        .IsUnique();

                    b.ToTable("formularios_calidad", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Hallazgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenteOrigen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ArtefactoEvaluadoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ArtefactoEvaluadoId");

                    b.ToTable("hallazgos", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Informe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuditoriaId");

                    b.ToTable("informes", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Procedimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("procedimientos", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.PromptAgente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenteKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsActiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModificadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModificadoPorUsuarioId");

                    b.HasIndex("AgenteKey", "EsActiva");

                    b.HasIndex("AgenteKey", "Version")
                        .IsUnique();

                    b.ToTable("prompts_agente", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClockifyProjectId")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("DriveFolderId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HorasEstimadas")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProcedimientoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoProyecto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrelloBoardId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoId");

                    b.ToTable("proyectos", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ProyectoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("proyectos_usuarios", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TemaPreferido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Claro");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEsperado", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Etapa", "Etapa")
                        .WithMany("ArtefactosEsperados")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEvaluado", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.ArtefactoEsperado", "ArtefactoEsperado")
                        .WithMany("ArtefactosEvaluados")
                        .HasForeignKey("ArtefactoEsperadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Auditoria", "Auditoria")
                        .WithMany("ArtefactosEvaluados")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtefactoEsperado");

                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Auditoria", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Etapa", "Etapa")
                        .WithMany("Auditorias")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Proyecto", "Proyecto")
                        .WithMany("Auditorias")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.AuditoriaProgreso", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Auditoria", "Auditoria")
                        .WithMany()
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.DocumentoAnalizado", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.ArtefactoEvaluado", "ArtefactoEvaluado")
                        .WithMany("DocumentosAnalizados")
                        .HasForeignKey("ArtefactoEvaluadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Auditoria", "Auditoria")
                        .WithMany("DocumentosAnalizados")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtefactoEvaluado");

                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Etapa", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Procedimiento", "Procedimiento")
                        .WithMany("Etapas")
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Hallazgo", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.ArtefactoEvaluado", "ArtefactoEvaluado")
                        .WithMany("Hallazgos")
                        .HasForeignKey("ArtefactoEvaluadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtefactoEvaluado");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Informe", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Auditoria", "Auditoria")
                        .WithMany("Informes")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.PromptAgente", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Usuario", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Proyecto", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Procedimiento", "Procedimiento")
                        .WithMany()
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ProyectoUsuario", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Proyecto", "Proyecto")
                        .WithMany("ProyectoUsuarios")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Usuario", "Usuario")
                        .WithMany("ProyectoUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEsperado", b =>
                {
                    b.Navigation("ArtefactosEvaluados");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEvaluado", b =>
                {
                    b.Navigation("DocumentosAnalizados");

                    b.Navigation("Hallazgos");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Auditoria", b =>
                {
                    b.Navigation("ArtefactosEvaluados");

                    b.Navigation("DocumentosAnalizados");

                    b.Navigation("Informes");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Etapa", b =>
                {
                    b.Navigation("ArtefactosEsperados");

                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Procedimiento", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Proyecto", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("ProyectoUsuarios");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("ProyectoUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
