// <auto-generated />
using System;
using ISOAuditAgent.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISOAuditAgent.API.Migrations
{
    [DbContext(typeof(ISOAuditAgentDbContext))]
    partial class ISOAuditAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEsperado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int")
                        .HasColumnName("etapa_id");

                    b.Property<bool>("MandatorioTipoA")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("mandatorio_tipo_a");

                    b.Property<bool>("MandatorioTipoB")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("mandatorio_tipo_b");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("PathTemplateRelativo")
                        .HasColumnType("longtext")
                        .HasColumnName("path_template_relativo");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.ToTable("artefactos_esperados");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEvaluado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aplica")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("aplica");

                    b.Property<int>("ArtefactoEsperadoId")
                        .HasColumnType("int")
                        .HasColumnName("artefacto_esperado_id");

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int")
                        .HasColumnName("auditoria_id");

                    b.Property<string>("JustificacionNoAplica")
                        .HasColumnType("longtext")
                        .HasColumnName("justificacion_no_aplica");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("observaciones");

                    b.Property<int>("Resultado")
                        .HasColumnType("int")
                        .HasColumnName("resultado");

                    b.HasKey("Id");

                    b.HasIndex("ArtefactoEsperadoId");

                    b.HasIndex("AuditoriaId");

                    b.ToTable("artefactos_evaluados");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int")
                        .HasColumnName("etapa_id");

                    b.Property<DateTime?>("FechaFinalizacionUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_finalizacion_utc");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio_utc");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("proyecto_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditorias");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ConfiguracionSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("configuraciones_sistema");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clave = "path_carpeta_templates",
                            Descripcion = "Ruta de la carpeta de templates de artefactos. Configurable por entorno: reemplazar el valor por la ruta real donde el deployment aloja los templates.",
                            Valor = "./templates"
                        });
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.DocumentoAnalizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtefactoEvaluadoId")
                        .HasColumnType("int")
                        .HasColumnName("artefacto_evaluado_id");

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int")
                        .HasColumnName("auditoria_id");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fuente");

                    b.Property<string>("HashContenido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hash_contenido");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("UrlReferencia")
                        .HasColumnType("longtext")
                        .HasColumnName("url_referencia");

                    b.HasKey("Id");

                    b.HasIndex("ArtefactoEvaluadoId");

                    b.HasIndex("AuditoriaId");

                    b.ToTable("documentos_analizados");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<int>("ProcedimientoId")
                        .HasColumnType("int")
                        .HasColumnName("procedimiento_id");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoId");

                    b.ToTable("etapas");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Hallazgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenteOrigen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("agente_origen");

                    b.Property<int>("ArtefactoEvaluadoId")
                        .HasColumnType("int")
                        .HasColumnName("artefacto_evaluado_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("justificacion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ArtefactoEvaluadoId");

                    b.ToTable("hallazgos");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Informe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditoriaId")
                        .HasColumnType("int")
                        .HasColumnName("auditoria_id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_generacion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AuditoriaId");

                    b.ToTable("informes");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Procedimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("procedimientos");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("ClockifyProjectId")
                        .HasColumnType("longtext")
                        .HasColumnName("clockify_project_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("DriveFolderId")
                        .HasColumnType("longtext")
                        .HasColumnName("drive_folder_id");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("HorasEstimadas")
                        .HasColumnType("int")
                        .HasColumnName("horas_estimadas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<int>("ProcedimientoId")
                        .HasColumnType("int")
                        .HasColumnName("procedimiento_id");

                    b.Property<string>("TipoProyecto")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("tipo_proyecto");

                    b.Property<string>("TrelloBoardId")
                        .HasColumnType("longtext")
                        .HasColumnName("trello_board_id");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoId");

                    b.ToTable("proyectos");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ProyectoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("proyecto_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProyectoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("proyecto_usuarios");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEsperado", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Etapa", "Etapa")
                        .WithMany("ArtefactosEsperados")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEvaluado", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.ArtefactoEsperado", "ArtefactoEsperado")
                        .WithMany("ArtefactosEvaluados")
                        .HasForeignKey("ArtefactoEsperadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Auditoria", "Auditoria")
                        .WithMany("ArtefactosEvaluados")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtefactoEsperado");

                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Auditoria", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Etapa", "Etapa")
                        .WithMany("Auditorias")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Proyecto", "Proyecto")
                        .WithMany("Auditorias")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.DocumentoAnalizado", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.ArtefactoEvaluado", "ArtefactoEvaluado")
                        .WithMany("DocumentosAnalizados")
                        .HasForeignKey("ArtefactoEvaluadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Auditoria", "Auditoria")
                        .WithMany("DocumentosAnalizados")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtefactoEvaluado");

                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Etapa", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Procedimiento", "Procedimiento")
                        .WithMany("Etapas")
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Hallazgo", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.ArtefactoEvaluado", "ArtefactoEvaluado")
                        .WithMany("Hallazgos")
                        .HasForeignKey("ArtefactoEvaluadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtefactoEvaluado");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Informe", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Auditoria", "Auditoria")
                        .WithMany("Informes")
                        .HasForeignKey("AuditoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auditoria");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Proyecto", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Procedimiento", "Procedimiento")
                        .WithMany()
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ProyectoUsuario", b =>
                {
                    b.HasOne("ISOAuditAgent.API.Models.Proyecto", "Proyecto")
                        .WithMany("ProyectoUsuarios")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISOAuditAgent.API.Models.Usuario", "Usuario")
                        .WithMany("ProyectoUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEsperado", b =>
                {
                    b.Navigation("ArtefactosEvaluados");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.ArtefactoEvaluado", b =>
                {
                    b.Navigation("DocumentosAnalizados");

                    b.Navigation("Hallazgos");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Auditoria", b =>
                {
                    b.Navigation("ArtefactosEvaluados");

                    b.Navigation("DocumentosAnalizados");

                    b.Navigation("Informes");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Etapa", b =>
                {
                    b.Navigation("ArtefactosEsperados");

                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Procedimiento", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Proyecto", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("ProyectoUsuarios");
                });

            modelBuilder.Entity("ISOAuditAgent.API.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("ProyectoUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
